sudo: false
language: scala
matrix:
  include:
    - jdk: oraclejdk9
      scala: 2.12.4
      script: sbt -Dsbt.scala.version=2.10.7 ++${TRAVIS_SCALA_VERSION} test:compile jvmParent/test "project jsParent" testSequential
