sudo: required

before_install:
- curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.0/bin/travis_setup.sh | bash -x

script:
# TODO "sbt nativeTest/run" invoke jvm main !?
- sbt ++2.11.11 "project nativeTest" "set nativeGC := \"$SCALANATIVE_GC\"" nativeLink
- for i in `seq 1 30` ; do echo "=============== $i =============" && ./native-test/target/scala-2.11/nativetest-out ; done


matrix:
  include:
  - os: linux
    dist: trusty
    jdk: oraclejdk8
    language: scala
    env: SCALANATIVE_GC=boehm

  - os: linux
    dist: trusty
    jdk: oraclejdk8
    language: scala
    env: SCALANATIVE_GC=immix

  - os: osx
    osx_image: xcode7.3
    env: SCALANATIVE_GC=boehm

  - os: osx
    osx_image: xcode7.3
    env: SCALANATIVE_GC=none

  - os: osx
    osx_image: xcode7.3
    env: SCALANATIVE_GC=immix
