name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 25
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - uses: coursier/cache-action@4e2615869d13561d626ed48655e1a39e5b192b3c # v6.4.7
    - run: ./sbt -v
           -Dsbt.traces=true
           -jvm-opts .github/workflows/.jvmopts
           "Test/compile"
    - run: ls -l target/traces
    - uses: xuwei-k/chrome-trace-to-mermaid-gantt@670b02a9c877411e1c251762357a5b6109ca5d1d
    - run: cat trade.md >> $GITHUB_STEP_SUMMARY
